// AUTO-GENERATED by scripts/build-plan-pdf-knowledge.js
// Regenerate with: node scripts/build-plan-pdf-knowledge.js
(function () {
  window.CHA_PLAN_PDF_MAP = [
  {
    "planId": "accesshealth",
    "planName": "Access Health STM",
    "type": "STM",
    "group": "Access Health",
    "aliases": [
      "Access Health STM",
      "access health stm",
      "accesshealth"
    ],
    "pdfFiles": [
      "Access_Health_STM.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "Access_Health_STM.pdf"
    ]
  },
  {
    "planId": "allstatecopayenhancedstm",
    "planName": "Allstate Copay Enhanced STM PPO Plan",
    "type": "STM",
    "group": "STM",
    "aliases": [
      "Allstate Copay Enhanced STM PPO Plan",
      "allstate copay enhanced stm ppo plan",
      "allstatecopayenhancedstm"
    ],
    "pdfFiles": [
      "Allstate_Copay_Enhanced_STM_PPO_Brochure.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "Allstate_Copay_Enhanced_STM_PPO_Brochure.pdf"
    ]
  },
  {
    "planId": "allstateenhancedstm",
    "planName": "Allstate Enhanced STM PPO Plan",
    "type": "STM",
    "group": "STM",
    "aliases": [
      "Allstate Enhanced STM PPO Plan",
      "allstate enhanced stm ppo plan",
      "allstateenhancedstm"
    ],
    "pdfFiles": [
      "Allstate_Enhanced_STM_PPO_Brochure.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "Allstate_Enhanced_STM_PPO_Brochure.pdf"
    ]
  },
  {
    "planId": "allstateessentialsstm",
    "planName": "Allstate Essentials STM PPO Plan",
    "type": "STM",
    "group": "STM",
    "aliases": [
      "Allstate Essentials STM PPO Plan",
      "allstate essentials stm ppo plan",
      "allstateessentialsstm"
    ],
    "pdfFiles": [
      "Allstate_Essentials_STM_PPO_Brochure.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "Allstate_Essentials_STM_PPO_Brochure.pdf"
    ]
  },
  {
    "planId": "allstatehealthaccess",
    "planName": "Allstate Health Access",
    "type": "Limited",
    "group": "Limited",
    "aliases": [
      "Allstate Health Access",
      "allstate health access",
      "allstatehealthaccess"
    ],
    "pdfFiles": [
      "Allstate_Health_Access_Brochure.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "Allstate_Health_Access_Brochure.pdf"
    ]
  },
  {
    "planId": "bwaamericare",
    "planName": "BWA Americare (2, 3, 4)",
    "type": "Limited",
    "group": "BWA",
    "aliases": [
      "BWA Americare (2, 3, 4)",
      "bwa americare",
      "bwaamericare",
      "BWA Americare"
    ],
    "pdfFiles": [
      "BWABrochurePlan2MBRAmericare2_REV.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "BWABrochurePlan2MBRAmericare2_REV.pdf"
    ]
  },
  {
    "planId": "bwapara",
    "planName": "BWA Paramount (MBR)",
    "type": "Limited",
    "group": "BWA",
    "aliases": [
      "BWA Paramount (MBR)",
      "bwa paramount",
      "bwapara",
      "BWA Paramount"
    ],
    "pdfFiles": [
      "BCS_Brochure_1.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "BCS_Brochure_1.pdf"
    ]
  },
  {
    "planId": "everest",
    "planName": "Everest Fixed Indemnity",
    "type": "Limited",
    "group": "Everest",
    "aliases": [
      "Everest Fixed Indemnity",
      "everest fixed indemnity",
      "everest",
      "Everest Fixed Indemnity (100–1000+)"
    ],
    "pdfFiles": [
      "Everest_Brochure_REV.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "Everest_Brochure_REV.pdf"
    ]
  },
  {
    "planId": "galena",
    "planName": "Galena STM Elite / Standard / Economy",
    "type": "STM",
    "group": "Galena",
    "aliases": [
      "Galena STM Elite / Standard / Economy",
      "galena stm elite standard economy",
      "galena"
    ],
    "pdfFiles": [
      "NEOSGIC_AFRP_STM_LimitedElite_1.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "NEOSGIC_AFRP_STM_LimitedElite_1.pdf"
    ]
  },
  {
    "planId": "ghdp1",
    "planName": "GoodHealth 1 (GHDP-1)",
    "type": "MEC",
    "group": "GoodHealth",
    "aliases": [
      "GoodHealth 1 (GHDP-1)",
      "goodhealth 1",
      "ghdp1",
      "GoodHealth 1",
      "GoodHealth1",
      "goodhealth1"
    ],
    "pdfFiles": [
      "MEC_GHDP1_1.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "ghdp2",
    "planName": "GoodHealth 2 (GHDP-2)",
    "type": "MEC",
    "group": "GoodHealth",
    "aliases": [
      "GoodHealth 2 (GHDP-2)",
      "goodhealth 2",
      "ghdp2",
      "GoodHealth 2",
      "GoodHealth2",
      "goodhealth2"
    ],
    "pdfFiles": [
      "MEC_GHDP2_1.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "ghdp3",
    "planName": "GoodHealth 3 (GHDP-3)",
    "type": "MEC",
    "group": "GoodHealth",
    "aliases": [
      "GoodHealth 3 (GHDP-3)",
      "goodhealth 3",
      "ghdp3",
      "GoodHealth 3",
      "GoodHealth3",
      "goodhealth3"
    ],
    "pdfFiles": [
      "MEC_GHDP3_1.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "ghdp4",
    "planName": "GoodHealth 4 (GHDP-4)",
    "type": "MEC",
    "group": "GoodHealth",
    "aliases": [
      "GoodHealth 4 (GHDP-4)",
      "goodhealth 4",
      "ghdp4",
      "GoodHealth 4",
      "GoodHealth4",
      "goodhealth4"
    ],
    "pdfFiles": [
      "MEC_GHDP4_1.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "ghdp5",
    "planName": "GoodHealth 5 (GHDP-5)",
    "type": "MEC",
    "group": "GoodHealth",
    "aliases": [
      "GoodHealth 5 (GHDP-5)",
      "goodhealth 5",
      "ghdp5",
      "GoodHealth 5",
      "GoodHealth5",
      "goodhealth5"
    ],
    "pdfFiles": [
      "MEC_GHDP5_2.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "harmonycare",
    "planName": "HarmonyCare PLUS",
    "type": "Limited",
    "group": "HarmonyCare",
    "aliases": [
      "HarmonyCare PLUS",
      "harmonycare plus",
      "harmonycare"
    ],
    "pdfFiles": [
      "HarmonyCarePLUS_Brochure_8949272987_V3_0625.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "medf1",
    "planName": "MedFirst 1",
    "type": "MEC",
    "group": "MedFirst",
    "aliases": [
      "MedFirst 1",
      "medfirst 1",
      "medf1",
      "MedFirst1",
      "medfirst1"
    ],
    "pdfFiles": [
      "MEC_MedFirst1_SPD_Jan25.pdf",
      "MEC_MedFirst1_SPDh_Jan25.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "MEC_MedFirst1_SPDh_Jan25.pdf"
    ]
  },
  {
    "planId": "medf2",
    "planName": "MedFirst 2",
    "type": "MEC",
    "group": "MedFirst",
    "aliases": [
      "MedFirst 2",
      "medfirst 2",
      "medf2",
      "MedFirst2",
      "medfirst2"
    ],
    "pdfFiles": [
      "MEC_MedFirst2_SPD_Jan25.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "medf3",
    "planName": "MedFirst 3",
    "type": "MEC",
    "group": "MedFirst",
    "aliases": [
      "MedFirst 3",
      "medfirst 3",
      "medf3",
      "MedFirst3",
      "medfirst3"
    ],
    "pdfFiles": [
      "MEC_MedFirst3_SPD_Jan25.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "medf4",
    "planName": "MedFirst 4",
    "type": "MEC",
    "group": "MedFirst",
    "aliases": [
      "MedFirst 4",
      "medfirst 4",
      "medf4",
      "MedFirst4",
      "medfirst4"
    ],
    "pdfFiles": [
      "MEC_MedFirst4_SPD_Jan25.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "medf5",
    "planName": "MedFirst 5",
    "type": "MEC",
    "group": "MedFirst",
    "aliases": [
      "MedFirst 5",
      "medfirst 5",
      "medf5",
      "MedFirst5",
      "medfirst5"
    ],
    "pdfFiles": [
      "MEC_MedFirst5_SPD_Jan25.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "mychoicehigh",
    "planName": "MyChoice - Plan High",
    "type": "Limited",
    "group": "Limited",
    "aliases": [
      "MyChoice - Plan High",
      "mychoice plan high",
      "mychoicehigh"
    ],
    "pdfFiles": [
      "MyChoice_High_Brochure_1.pdf"
    ],
    "status": "excluded",
    "missingFiles": [],
    "exclusionReason": "missing_pdf_by_scope_decision"
  },
  {
    "planId": "mychoicelow",
    "planName": "MyChoice - Plan Low",
    "type": "Limited",
    "group": "Limited",
    "aliases": [
      "MyChoice - Plan Low",
      "mychoice plan low",
      "mychoicelow"
    ],
    "pdfFiles": [
      "MyChoice_Low_Brochure_1.pdf"
    ],
    "status": "excluded",
    "missingFiles": [],
    "exclusionReason": "missing_pdf_by_scope_decision"
  },
  {
    "planId": "mychoicemid",
    "planName": "MyChoice - Plan Mid",
    "type": "Limited",
    "group": "Limited",
    "aliases": [
      "MyChoice - Plan Mid",
      "mychoice plan mid",
      "mychoicemid"
    ],
    "pdfFiles": [
      "MyChoice_Mid_Brochure_1.pdf"
    ],
    "status": "excluded",
    "missingFiles": [],
    "exclusionReason": "missing_pdf_by_scope_decision"
  },
  {
    "planId": "healthchoicesilver",
    "planName": "NCE Health Choice Silver",
    "type": "Limited",
    "group": "NCE Health Choice",
    "aliases": [
      "NCE Health Choice Silver",
      "nce health choice silver",
      "healthchoicesilver"
    ],
    "pdfFiles": [
      "HealthChoiceSilverBrochure2.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "pinnaclecriticalcare1",
    "planName": "Pinnacle Critical Care Plan 1",
    "type": "Limited",
    "group": "Limited",
    "aliases": [
      "Pinnacle Critical Care Plan 1",
      "pinnacle critical care plan 1",
      "pinnaclecriticalcare1",
      "Pinnacle Critical Care Plan1",
      "pinnacle critical care plan1"
    ],
    "pdfFiles": [
      "Pinnacle_CriticalCare_Plan1_Brochure.pdf"
    ],
    "status": "excluded",
    "missingFiles": [],
    "exclusionReason": "missing_pdf_by_scope_decision"
  },
  {
    "planId": "pinnaclecriticalcare2",
    "planName": "Pinnacle Critical Care Plan 2",
    "type": "Limited",
    "group": "Limited",
    "aliases": [
      "Pinnacle Critical Care Plan 2",
      "pinnacle critical care plan 2",
      "pinnaclecriticalcare2",
      "Pinnacle Critical Care Plan2",
      "pinnacle critical care plan2"
    ],
    "pdfFiles": [
      "Pinnacle_CriticalCare_Plan2_Brochure.pdf"
    ],
    "status": "excluded",
    "missingFiles": [],
    "exclusionReason": "missing_pdf_by_scope_decision"
  },
  {
    "planId": "pinnaclecriticalcare3",
    "planName": "Pinnacle Critical Care Plan 3",
    "type": "Limited",
    "group": "Limited",
    "aliases": [
      "Pinnacle Critical Care Plan 3",
      "pinnacle critical care plan 3",
      "pinnaclecriticalcare3",
      "Pinnacle Critical Care Plan3",
      "pinnacle critical care plan3"
    ],
    "pdfFiles": [
      "Pinnacle_CriticalCare_Plan3_Brochure.pdf"
    ],
    "status": "excluded",
    "missingFiles": [],
    "exclusionReason": "missing_pdf_by_scope_decision"
  },
  {
    "planId": "pinnaclecriticalcare4",
    "planName": "Pinnacle Critical Care Plan 4",
    "type": "Limited",
    "group": "Limited",
    "aliases": [
      "Pinnacle Critical Care Plan 4",
      "pinnacle critical care plan 4",
      "pinnaclecriticalcare4",
      "Pinnacle Critical Care Plan4",
      "pinnacle critical care plan4"
    ],
    "pdfFiles": [
      "Pinnacle_CriticalCare_Plan4_Brochure.pdf"
    ],
    "status": "excluded",
    "missingFiles": [],
    "exclusionReason": "missing_pdf_by_scope_decision"
  },
  {
    "planId": "pinnacleprotect1",
    "planName": "Pinnacle Protect Plan 1",
    "type": "Limited",
    "group": "Limited",
    "aliases": [
      "Pinnacle Protect Plan 1",
      "pinnacle protect plan 1",
      "pinnacleprotect1",
      "Pinnacle Protect Plan1",
      "pinnacle protect plan1"
    ],
    "pdfFiles": [
      "Pinnacle_Protect_Plan1_Brochure.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "Pinnacle_Protect_Plan1_Brochure.pdf"
    ]
  },
  {
    "planId": "pinnacleprotect2",
    "planName": "Pinnacle Protect Plan 2",
    "type": "Limited",
    "group": "Limited",
    "aliases": [
      "Pinnacle Protect Plan 2",
      "pinnacle protect plan 2",
      "pinnacleprotect2",
      "Pinnacle Protect Plan2",
      "pinnacle protect plan2"
    ],
    "pdfFiles": [
      "Pinnacle_Protect_Plan2_Brochure.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "Pinnacle_Protect_Plan2_Brochure.pdf"
    ]
  },
  {
    "planId": "pinnacleprotect3",
    "planName": "Pinnacle Protect Plan 3",
    "type": "Limited",
    "group": "Limited",
    "aliases": [
      "Pinnacle Protect Plan 3",
      "pinnacle protect plan 3",
      "pinnacleprotect3",
      "Pinnacle Protect Plan3",
      "pinnacle protect plan3"
    ],
    "pdfFiles": [
      "Pinnacle_Protect_Plan3_Brochure.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "Pinnacle_Protect_Plan3_Brochure.pdf"
    ]
  },
  {
    "planId": "pinnacleprotect4",
    "planName": "Pinnacle Protect Plan 4",
    "type": "Limited",
    "group": "Limited",
    "aliases": [
      "Pinnacle Protect Plan 4",
      "pinnacle protect plan 4",
      "pinnacleprotect4",
      "Pinnacle Protect Plan4",
      "pinnacle protect plan4"
    ],
    "pdfFiles": [
      "Pinnacle_Protect_Plan4_Brochure.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "Pinnacle_Protect_Plan4_Brochure.pdf"
    ]
  },
  {
    "planId": "pinnacle",
    "planName": "Pinnacle STM",
    "type": "STM",
    "group": "Pinnacle",
    "aliases": [
      "Pinnacle STM",
      "pinnacle stm",
      "pinnacle"
    ],
    "pdfFiles": [
      "Pinnacle_STM_Brochure.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "Pinnacle_STM_Brochure.pdf"
    ]
  },
  {
    "planId": "sigmacare",
    "planName": "SigmaCare Plus",
    "type": "Limited",
    "group": "SigmaCare",
    "aliases": [
      "SigmaCare Plus",
      "sigmacare plus",
      "sigmacare"
    ],
    "pdfFiles": [
      "AFSLIC20_SCP_Brochure_rev.pdf"
    ],
    "status": "excluded",
    "missingFiles": [],
    "exclusionReason": "missing_pdf_by_scope_decision"
  },
  {
    "planId": "smartchoice2500",
    "planName": "Smart Choice",
    "type": "MEC",
    "group": "Smart Choice",
    "aliases": [
      "Smart Choice",
      "smart choice",
      "smartchoice2500"
    ],
    "pdfFiles": [
      "Smart_Choice_2500_Plan_Doc_2025__.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "Smart_Choice_2500_Plan_Doc_2025__.pdf"
    ]
  },
  {
    "planId": "smartchoice1500",
    "planName": "Smart Choice 1500",
    "type": "MEC",
    "group": "MEC",
    "aliases": [
      "Smart Choice 1500",
      "smart choice 1500",
      "smartchoice1500",
      "Smart Choice1500",
      "smart choice1500"
    ],
    "pdfFiles": [
      "Smart_Choice_1500_Plan_Doc_2025.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "Smart_Choice_1500_Plan_Doc_2025.pdf"
    ]
  },
  {
    "planId": "smartchoice3000",
    "planName": "Smart Choice 3000",
    "type": "MEC",
    "group": "MEC",
    "aliases": [
      "Smart Choice 3000",
      "smart choice 3000",
      "smartchoice3000",
      "Smart Choice3000",
      "smart choice3000"
    ],
    "pdfFiles": [
      "Smart_Choice_3000_Plan_Doc_2025.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "Smart_Choice_3000_Plan_Doc_2025.pdf"
    ]
  },
  {
    "planId": "smartchoice3500",
    "planName": "Smart Choice 3500",
    "type": "MEC",
    "group": "MEC",
    "aliases": [
      "Smart Choice 3500",
      "smart choice 3500",
      "smartchoice3500",
      "Smart Choice3500",
      "smart choice3500"
    ],
    "pdfFiles": [
      "Smart_Choice_3500_Plan_Doc_2025.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "Smart_Choice_3500_Plan_Doc_2025.pdf"
    ]
  },
  {
    "planId": "smarthealth",
    "planName": "Smart Health STM",
    "type": "STM",
    "group": "Smart Health",
    "aliases": [
      "Smart Health STM",
      "smart health stm",
      "smarthealth"
    ],
    "pdfFiles": [
      "SmartHealth_v3.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "SmartHealth_v3.pdf"
    ]
  },
  {
    "planId": "tdk1",
    "planName": "TDK 1",
    "type": "MEC",
    "group": "TDK",
    "aliases": [
      "TDK 1",
      "tdk 1",
      "tdk1",
      "TDK1"
    ],
    "pdfFiles": [
      "TDK_Promo_Combined.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "tdk2",
    "planName": "TDK 2",
    "type": "MEC",
    "group": "TDK",
    "aliases": [
      "TDK 2",
      "tdk 2",
      "tdk2",
      "TDK2"
    ],
    "pdfFiles": [
      "TDK_Promo_Combined.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "tdk3",
    "planName": "TDK 3",
    "type": "MEC",
    "group": "TDK",
    "aliases": [
      "TDK 3",
      "tdk 3",
      "tdk3",
      "TDK3"
    ],
    "pdfFiles": [
      "TDK_Promo_Combined.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "tdk4",
    "planName": "TDK 4",
    "type": "MEC",
    "group": "TDK",
    "aliases": [
      "TDK 4",
      "tdk 4",
      "tdk4",
      "TDK4"
    ],
    "pdfFiles": [
      "TDK_Promo_Combined.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "tdk5",
    "planName": "TDK 5",
    "type": "MEC",
    "group": "TDK",
    "aliases": [
      "TDK 5",
      "tdk 5",
      "tdk5",
      "TDK5"
    ],
    "pdfFiles": [
      "TDK_Promo_Combined.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "trueh1",
    "planName": "TrueHealth 1",
    "type": "MEC",
    "group": "TrueHealth",
    "aliases": [
      "TrueHealth 1",
      "truehealth 1",
      "trueh1",
      "TrueHealth1",
      "truehealth1"
    ],
    "pdfFiles": [
      "MEC_TrueHealth1_SPD_Jan25.pdf"
    ],
    "status": "ready",
    "missingFiles": []
  },
  {
    "planId": "trueh2",
    "planName": "TrueHealth 2",
    "type": "MEC",
    "group": "MEC",
    "aliases": [
      "TrueHealth 2",
      "truehealth 2",
      "trueh2",
      "TrueHealth2",
      "truehealth2"
    ],
    "pdfFiles": [
      "MEC_TrueHealth2_SPD_Jan25.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "MEC_TrueHealth2_SPD_Jan25.pdf"
    ]
  },
  {
    "planId": "trueh3",
    "planName": "TrueHealth 3",
    "type": "MEC",
    "group": "MEC",
    "aliases": [
      "TrueHealth 3",
      "truehealth 3",
      "trueh3",
      "TrueHealth3",
      "truehealth3"
    ],
    "pdfFiles": [
      "MEC_TrueHealth3_SPD_Jan25.pdf"
    ],
    "status": "missing_pdf",
    "missingFiles": [
      "MEC_TrueHealth3_SPD_Jan25.pdf"
    ]
  }
];
  window.CHA_PLAN_ALIAS_INDEX = {
  "access health stm": "accesshealth",
  "accesshealth": "accesshealth",
  "allstate copay enhanced stm ppo plan": "allstatecopayenhancedstm",
  "allstatecopayenhancedstm": "allstatecopayenhancedstm",
  "allstate enhanced stm ppo plan": "allstateenhancedstm",
  "allstateenhancedstm": "allstateenhancedstm",
  "allstate essentials stm ppo plan": "allstateessentialsstm",
  "allstateessentialsstm": "allstateessentialsstm",
  "allstate health access": "allstatehealthaccess",
  "allstatehealthaccess": "allstatehealthaccess",
  "bwa americare": "bwaamericare",
  "bwaamericare": "bwaamericare",
  "bwa paramount": "bwapara",
  "bwapara": "bwapara",
  "everest fixed indemnity": "everest",
  "everest": "everest",
  "galena stm elite standard economy": "galena",
  "galena": "galena",
  "goodhealth 1": "ghdp1",
  "ghdp1": "ghdp1",
  "goodhealth1": "ghdp1",
  "goodhealth 2": "ghdp2",
  "ghdp2": "ghdp2",
  "goodhealth2": "ghdp2",
  "goodhealth 3": "ghdp3",
  "ghdp3": "ghdp3",
  "goodhealth3": "ghdp3",
  "goodhealth 4": "ghdp4",
  "ghdp4": "ghdp4",
  "goodhealth4": "ghdp4",
  "goodhealth 5": "ghdp5",
  "ghdp5": "ghdp5",
  "goodhealth5": "ghdp5",
  "harmonycare plus": "harmonycare",
  "harmonycare": "harmonycare",
  "medfirst 1": "medf1",
  "medf1": "medf1",
  "medfirst1": "medf1",
  "medfirst 2": "medf2",
  "medf2": "medf2",
  "medfirst2": "medf2",
  "medfirst 3": "medf3",
  "medf3": "medf3",
  "medfirst3": "medf3",
  "medfirst 4": "medf4",
  "medf4": "medf4",
  "medfirst4": "medf4",
  "medfirst 5": "medf5",
  "medf5": "medf5",
  "medfirst5": "medf5",
  "mychoice plan high": "mychoicehigh",
  "mychoicehigh": "mychoicehigh",
  "mychoice plan low": "mychoicelow",
  "mychoicelow": "mychoicelow",
  "mychoice plan mid": "mychoicemid",
  "mychoicemid": "mychoicemid",
  "nce health choice silver": "healthchoicesilver",
  "healthchoicesilver": "healthchoicesilver",
  "pinnacle critical care plan 1": "pinnaclecriticalcare1",
  "pinnaclecriticalcare1": "pinnaclecriticalcare1",
  "pinnacle critical care plan1": "pinnaclecriticalcare1",
  "pinnacle critical care plan 2": "pinnaclecriticalcare2",
  "pinnaclecriticalcare2": "pinnaclecriticalcare2",
  "pinnacle critical care plan2": "pinnaclecriticalcare2",
  "pinnacle critical care plan 3": "pinnaclecriticalcare3",
  "pinnaclecriticalcare3": "pinnaclecriticalcare3",
  "pinnacle critical care plan3": "pinnaclecriticalcare3",
  "pinnacle critical care plan 4": "pinnaclecriticalcare4",
  "pinnaclecriticalcare4": "pinnaclecriticalcare4",
  "pinnacle critical care plan4": "pinnaclecriticalcare4",
  "pinnacle protect plan 1": "pinnacleprotect1",
  "pinnacleprotect1": "pinnacleprotect1",
  "pinnacle protect plan1": "pinnacleprotect1",
  "pinnacle protect plan 2": "pinnacleprotect2",
  "pinnacleprotect2": "pinnacleprotect2",
  "pinnacle protect plan2": "pinnacleprotect2",
  "pinnacle protect plan 3": "pinnacleprotect3",
  "pinnacleprotect3": "pinnacleprotect3",
  "pinnacle protect plan3": "pinnacleprotect3",
  "pinnacle protect plan 4": "pinnacleprotect4",
  "pinnacleprotect4": "pinnacleprotect4",
  "pinnacle protect plan4": "pinnacleprotect4",
  "pinnacle stm": "pinnacle",
  "pinnacle": "pinnacle",
  "sigmacare plus": "sigmacare",
  "sigmacare": "sigmacare",
  "smart choice": "smartchoice2500",
  "smartchoice2500": "smartchoice2500",
  "smart choice 1500": "smartchoice1500",
  "smartchoice1500": "smartchoice1500",
  "smart choice1500": "smartchoice1500",
  "smart choice 3000": "smartchoice3000",
  "smartchoice3000": "smartchoice3000",
  "smart choice3000": "smartchoice3000",
  "smart choice 3500": "smartchoice3500",
  "smartchoice3500": "smartchoice3500",
  "smart choice3500": "smartchoice3500",
  "smart health stm": "smarthealth",
  "smarthealth": "smarthealth",
  "tdk 1": "tdk1",
  "tdk1": "tdk1",
  "tdk 2": "tdk2",
  "tdk2": "tdk2",
  "tdk 3": "tdk3",
  "tdk3": "tdk3",
  "tdk 4": "tdk4",
  "tdk4": "tdk4",
  "tdk 5": "tdk5",
  "tdk5": "tdk5",
  "truehealth 1": "trueh1",
  "trueh1": "trueh1",
  "truehealth1": "trueh1",
  "truehealth 2": "trueh2",
  "trueh2": "trueh2",
  "truehealth2": "trueh2",
  "truehealth 3": "trueh3",
  "trueh3": "trueh3",
  "truehealth3": "trueh3"
};
})();
